server.port=38080
logging.level.root=debug

#langchain4j.open-ai.chat-model.base-url=http://langchain4j.dev/demo/openai/v1
#langchain4j.open-ai.chat-model.api-key=demo
#langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

#langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com/v1
#langchain4j.open-ai.chat-model.api-key=sk-ad89fcb9f9bd484f8bbcdb3ba9a9ba041
#langchain4j.open-ai.chat-model.model-name=deepseek-chat
#langchain4j.open-ai.chat-model.model-name=deepseek-reasoner

# 应用程序发送给大模型的请求日志和响应日志
#langchain4j.open-ai.chat-model.log-requests=true
#langchain4j.open-ai.chat-model.log-responses=true



#ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=deepseek-r1:1.5b
langchain4j.ollama.chat-model.temperature=0.8
langchain4j.ollama.chat-model.timeout=PT60S

langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true